### ISSUE TITLE
Feature Request: Git integration and management for DataTemplates

### ISSUE THREAD

**Issue by netopsengineer** [cmason3/jinjafx_server#10]
Good afternoon @cmason3,

I continue to find amazing value with jinjafx + the server side component of the tool, your attention to detail and features demonstrate your commitment to the developer experience when using the tool, great work!  I was wondering if you had considered adding Git support as a repository option for `-r`?  

The goal would be to allow users, who might not be as developer skilled, to help develop and maintain the `DataTemplates` in a friendly UI with live templating like `jinjafx` provides, so network engineers for example, who know the network configuration that should be contained in the template and the dataset, versus a backend developer who knows nothing about network engineering, who is utilizing the resultant output from the templates for another tool/purpose.

Here are some rough draft thoughts I had about how this might look, but by all means open to all suggestions and improvements/considerations. 

As a **[developer]** I would like the ability to maintain the lifecycle of `DataTemplates` with Git, and those functions be initiated from the UI, so that **[users]** can select from a list of repositories in the UI, which should contain only `DataTemplates`.  The **[developer]** should provide a list of repositories, any required branch, and authentication parameters in a configuration file initialized on invocation of `jinjafx_server`, upon initialization, those repo's should be cloned if they don't currently exist in the `jinjafx_server` path.  

The proposed `jinjafx_server` solution should perform a `git pull` on the appropriate repo as selected by the **[user]**, to sync any pending changes since the last invocation of `jinjafx_server`, before dynamically populating a new selection element/drop down of `DataTemplates` contained within the currently selected repo.  Upon selection of a `DataTemplate`, `jinjafx_server` should restore the `template`, and `dataset(s)` as chosen by the **[user]** and continue to operate as it does today, links, export, generate, and so forth.   

> Since the repos have been cloned already, and only incremental changes would be pulled, this process should keep the data in sync, and still maintain good performance when selecting a repo with pending changes, and Git should ignore pull attempts with no pending upstream changes.

The `jinjafx_server` solution would also provide a UI initiated mechanism allowing the **[user]** to submit changes/revisions to the `DataTemplate` via Git, where `jinjafx_server` should perform a `git commit` and a `git push`, allowing the repo's currently configured pull request/merge process to take place on the back end, and run any pipelines to verify integrity, and ultimately merge back into the repo.

> There is a slight risk where with just the right timing, I could have committed a change to the same template the user is working on if we are working from one branch, and Git would trigger a merge conflict, unless each change was processed under a fork of the repo, so perhaps a fork should be created for user changes that is then committed, and pushed.  I'm open to ideas here as I'm not quite sure what the best way to keep the conflicts to a minimum might be.

**Comment by cmason3** [comment]
Brilliant idea - I need to think how this could be achieved in the UI to make it seamless for the user - getting this right isn’t a 5 minute job. In a previous project I did implement GitLab integration via the GitLab API over HTTPS as this allows you to fetch and push individual files, but it wasn’t standard Git. I much prefer using the Git protocol so it works with different Git repositories and not just GitHub.

It would be relatively easy to specify a Git repository on the command line via `-r` and specify a Private Access Token in an environment variable, but this would then use the same repo for all DataTemplates, but it would require minimal changes to the UI.

As you have detailed, there is a need to `git pull` to ensure the repository is up to date as well as a risk of conflicting changes if someone else has modified the repository. I will have a think about it and see what I can do.

**Comment by netopsengineer** [comment]
Awesome! There are so many great design and power user centric details in this tool, I'm excited, and not surprised that this has crossed your mind already at some point.

I'm watching the thread, so if you have questions, or need some insight, or to try a beta version, I'm here to help dial it in.  As you mentioned, not a 5 minute thing, and definitely worth doing right, together I think we can design something iteratively that adds alot of functionality, not only the version control itself, but a new audience for the tool by lowering the barrier to entry on the care and feeding of the templates and datasets!

**Comment by cmason3** [comment]
Using a GitHub repository to store DataTemplates has been added via the GitHub API with the `-github` command line option to version `22.11.3`. This works similar to AWS S3 integration, but allows you to maintain changes and commit history within a GitHub repository, e.g:

```
export GITHUB_TOKEN="<github_token>"
./jinjafx_server.py -s -l 0.0.0.0 -github <owner>/<repo>[:<branch>]
```

At this point I don't have time to look at full Git integration as it has numerous challenges around user interface and how we manage merge conflicts of the cloned Git repository vs the upstream version. I might come back to it at some point, but it won't be in the short term.
